#ifndef STARSTIMAPI_GLOBAL_H
#define STARSTIMAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STARSTIMAPI_LIBRARY)
#  define STARSTIMAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define STARSTIMAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STARSTIMAPI_GLOBAL_H
